[package]
name = "specs_practice"
version = "0.1.0"
authors = ["pallaria"]
edition = "2018"

[dependencies]
# specs = "0.16.1"
specs-derive = "0.4.1"
specs = { version = "0.16.1", features = ["shred-derive", "specs-derive"] }
